### ISSUE TITLE
日期多选功能

### ISSUE THREAD

**Issue by Liyuk** [luqin/react-bootstrap-datetimerangepicker#1]
能新增一个单个日期 多选 的功能么？
就是能多次选择不同的日期，而不是时间段

**Comment by luqin** [comment]
这需求有点变态啊，目前是不支持日期多选的，可以基于此插件实现一个类似tag标签输入的功能，你有什么好的思路吗？

**Comment by Liyuk** [comment]
感觉类似tag的输入是一条实现思路，实现可以参考下https://github.com/eternicode/bootstrap-datepicker，可以去sadbox看一下效果。实现大致思路是：通过配置multidate开启，在点击时进行一次判断，如果开启了multidate调用对应的事件处理_toggle_multidate（将选中日期加入array，并通过setValue显示在input框中）。可以去online demo的sandbox里面试一下效果，http://dwz.cn/2q3HDY。

**Comment by Liyuk** [comment]
另外还有个疑问，选择时间段的时候，选择开始时间（9月10日），选择结束时间（11月1日），结束时间在第二个面板上处于灰色，点击之后input框变化了，但是面板没有自动跳转（切换到11月）。这算是个坑么？还是我用法太奇怪了。

**Comment by Liyuk** [comment]
感觉类似tag的输入是一条实现思路。  
实现可以参考下这个[datepicker](https://github.com/eternicode/bootstrap-datepicker)。  
可以去online demo的[sandbox](http://dwz.cn/2q3HDY)里面试一下效果。  
实现大致思路是：

> 通过配置multidate开启，在点击时进行一次判断；  
> 如果开启了multidate调用对应的事件处理_toggle_multidate；  
> 将选中日期加入array，并通过setValue显示在input框中）。

**Comment by luqin** [comment]
时间多选使用单时间选择还不错，不过现在的日期选择在年月及时间选择不够漂亮。

**Comment by luqin** [comment]
选中结束日期未切换到对应面板是因为输入框自动到开始日期了
