### ISSUE TITLE
It's not work with react v16.0.0

### ISSUE THREAD

**Issue by threescales** [luqin/react-bootstrap-datetimerangepicker#13]
"react-bootstrap-datetimerangepicker@2.0.4"

import DatetimeRangePicker from 'react-bootstrap-datetimerangepicker'

![image](https://user-images.githubusercontent.com/15061441/31007942-e050c61c-a4c7-11e7-9ef4-3c20ede339cc.png)

**Comment by cmyers** [comment]
This is due to the latest version not being published to npm due to build errors. I've corrected the errors which were due to package problems and submitted a pull request. New to github so I'm not sure if I've done this all correctly.
