### ISSUE TITLE
Timepicker to show default time in GMT

### ISSUE THREAD

**Issue by NehaSharma2304** [luqin/react-bootstrap-datetimerangepicker#16]
Using this library I am trying to show default from and to date into GMT along with time. Is there any way to set default time in GMT

**Comment by cmyers** [comment]
You could use moment.js and set the locale then pass the moment dates into the startDate and endDate props.

**Comment by NehaSharma2304** [comment]
In my locale I am doing this  
const locale = {           
            format: 'YYYY-MM-DD HH:mm',
            separator: ' - ',
            applyLabel: 'Apply',
            cancelLabel: 'Cancel'
        };

And library offers below locale, doesnt have timezone option
options.locale = {
        format: 'MM/DD/YYYY HH:mm',
        separator: ' - ',
        applyLabel: 'Apply',
        cancelLabel: 'Cancel',
        fromLabel: 'From',
        toLabel: 'To',
        customRangeLabel: 'Custom',
        daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
        monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        firstDay: 1
      };

**Comment by NehaSharma2304** [comment]
And is it possible to show, something like if user in PST from timepicker should show 7:00am and to timepicker show GMT time according to PST?

**Comment by cmyers** [comment]
Yes locale prop just sets the format for displaying.

If you want to change the timezone of the time passed in by the browser you can use moment().tz. See https://momentjs.com/guides/ which has some examples. Then just pass those converted dates into your startDate and endDate props as required.

**Comment by NehaSharma2304** [comment]
aahh able to do it using, startdate and endDate :). cmyers2016 thanks for the help :)
<DatetimeRangePicker
timePicker
showDropdowns
timePicker24Hour
startDate={moment().subtract(1, 'days').utc().format('YYYY-MM-DD HH:mm')}
endDate={moment().utc().format('YYYY-MM-DD HH:mm')}
/>
