### ISSUE TITLE
singleDatePicker - Change date from input.

### ISSUE THREAD

**Issue by mauridirecta24** [luqin/react-bootstrap-datetimerangepicker#31]
Hi All,

Im using the dateragepicker on my react app. Im using the singleDatePicker property. 
I want to be able to edit the date from the input using keyboard.

when I click on the input I see the cursor, but when I hit backspace to remove the date "1969-12-31".

![image](https://user-images.githubusercontent.com/59965104/72531114-92854200-384f-11ea-91bf-406fe760a13c.png)

Then if I remove the date by selecting and backspace key I get invalid date on the input and the datepicker goes into an invalid state:

![image](https://user-images.githubusercontent.com/59965104/72530921-27d40680-384f-11ea-8ff4-805064a3aa9b.png)

This is the rage picker component Im using:

` <DateRangePicker
        startDate={startDate}
        singleDatePicker
        maxDate={maxDate}
        containerStyles={{ display: 'block' }}
        locale={locale}
        opens={opensTo}
        drops={dropsTo}
        maxSpan={maxSpan}
        alwaysShowCalendars
        onApply={this.handleApply}
        onCancel={this.handleCancel}
      >
        <TextInput
          field={{ ...field, value: start }}
          form={form}
          icon={'calendar'}
        />
      </DateRangePicker>`

Can any one help me on find a solution to this? 

Thanks!

**Comment by luqin** [comment]
Only support bootstrap-daterangepicker 2.1.19+

**Comment by mauridirecta24** [comment]
@luqin  I dont think it is a version issue.

I have on the pakage.json this version:

    "bootstrap-daterangepicker": "^3.0.5",

But still i cant edit the date manually.

I checked the demo page:

https://projects.skratchdot.com/react-bootstrap-daterangepicker/?knob-label=click%20to%20open&knob-singleDatePicker=true&selectedKind=DateRangePicker&selectedStory=singleDatePicker&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

But in that demo the date picker does not have an input. So is not the same scenario as the one Im looking for.

Thanks!
