### ISSUE TITLE
warnings on properties with react 15.2

### ISSUE THREAD

**Issue by InsidiousForce** [luqin/react-bootstrap-datetimerangepicker#5]
see:

https://github.com/zippyui/react-date-picker/issues/117

Same issue here. on react 15.2 you get a warning about properties.

Warning: Unknown props `startDate`, `endDate`, `showDropdowns`, `linkedCalendars`, `opens`, `locale`, `ranges`, `onEvent`, `alwaysShowCalendars`, `template` on div tag. Remove these props from the element.

**Comment by Pipoupi** [comment]
+1

**Comment by pointblack** [comment]
+1
